version: "3.9"

services:
  book-service:
    build: ./book-service
    ports:
      - "${BOOK_SERVICE_PORT}:8081"
    env_file:
      - bs.env
  notification-service:
    build: ./notification-service
    env_file:
      - ns.env
  db:
    image: postgres:15
    container_name: book_db
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - "zookeeper"
volumes:
  postgres_data:
